export const API_FETCHING_REQUEST = 'API_FETCHING_REQUEST';
export const SAGA_GET_DATA = 'SAGA_GET_DATA';
export const SAGA_GET_DATA_ASYNC = 'SAGA_GET_DATA_ASYNC';
export const SAGA_POST_DATA = 'SAGA_POST_DATA';
export const SAGA_POST_DATA_ASYNC = 'SAGA_POST_DATA_ASYNC';
export const SAGA_DELETE_DATA = 'SAGA_DELETE_DATA';
export const SAGA_DELETE_DATA_ASYNC = 'SAGA_DELETE_DATA_ASYNC';

// another saga Constant:

export const SAGA_GOGET_DATA = 'SAGA_GOGET_DATA';
export const SAGA_GOGET_DATA_ASYNC = 'SAGA_GOGET_DATA_ASYNC';
export const SAGA_GOPOST_DATA = 'SAGA_GOPOST_DATA';
export const SAGA_GOPOST_DATA_ASYNC = 'SAGA_GOPOST_DATA_ASYNC';
export const SAGA_GODELETE_DATA = 'SAGA_GODELETE_DATA';
export const SAGA_GODELETE_DATA_ASYNC = 'SAGA_GODELETE_DATA_ASYNC';
